export enum ColorEnum {
  Beige = "beige",
  Claret = "claret",
  Red = "red",
  Gray = "gray",
  Yellow = "yellow",
  White = "white",
  Brown = "brown",
  Purple = "purple",
  Blue = "blue",
  Silver = "silver",
  Golden = "golden",
  Black = "black",
  Navy = "navy",
  Orange = "orange",
  Green = "green",
  Other = "other",
}
